services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    init: true
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - api
    init: true
